version: '3'

services:
    db:
        image: postgres
        environment: 
            - POSTGRES_PASSWORD=azerty
    script:
        image: fn-apply-views
        build: .
        depends_on: 
            - db